config/routes.rb
Rails.application.routes.draw do
  get 'dirlogin/pagein'
  post 'dirlogin/pagein'

  get 'dirlogin/pageout'
  post 'dirlogin/pageout'
    
    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy 
    end

  resources :users
  get 'showprodcusts/prodcustin'
  post 'showprodcusts/prodcustin'

  get 'showprodcusts/prodcustout'
  post 'showprodcusts/prodcustout'

  get 'showcustprods/custprodout'
  post 'showcustprods/custprodout'

  get 'showcustprods/custprodin'
  post 'showcustprods/custprodin'

  resources :orders
  resources :products
  resources :customers
  resources :brands
  resources :categories
  resources :states
  get 'dbtables/showdbtables'
    
  get 'sessions/new'

  get 'mainusers/login'

  get 'mainusers/accept'

  get 'mainusers/denial'

  get 'home/index'

  get 'home/catalog'

  get 'flash/flashpage'

    root :to => 'home#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
    validates :brandname, presence: true, uniqueness: true
    validates :brandcontact, presence: true
    
    has_many :product, dependent:  :destroy
    
end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :categoryname, presence: true, uniqueness: true
    validates :categorydescription, presence: true, uniqueness: true
    
    has_many :product, dependent:  :destroy
    
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    validates :firstname, presence: true
    validates :lastname, presence: true
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :phone, presence: true, length: {:is => 10}
    validates :address, presence: true
    validates :city, presence: true
    validates :state_id, presence: true

    has_many :product, :through => :order
    has_many :order, dependent:  :destroy
    
    belongs_to :state
    
    def name
	"#{lastname }, #{firstname}"
    end

    
end

app/models/order.rb
class Order < ActiveRecord::Base
    validates :customer_id, presence: true
    validates :product_id, presence: true
    
    belongs_to :customer
    belongs_to :product
    
end

app/models/product.rb
class Product < ActiveRecord::Base
    validates :productname, presence: true, uniqueness: true
    validates :productimage, presence: true, uniqueness: true
    validates :productdescription, presence: true
    validates :category_id, presence: true
    validates :brand_id, presence: true
    validates :price, presence: true, numericality: true
    validates :status, presence: true
    
    has_many :order
    has_many :customer, :through => :order 
    
    belongs_to :category
    belongs_to :brand
    
end

app/models/state.rb
class State < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_filter :authorize
    
  def index
  end

  def catalog
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:statename, :abbreviation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dbtables_helper.rb
module DbtablesHelper
end

app/helpers/dirlogin_helper.rb
module DirloginHelper
end

app/helpers/flash_helper.rb
module FlashHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mainusers_helper.rb
module MainusersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :statename %><br>
    <%= f.text_field :statename %>
  </div>
  <div class="field">
    <%= f.label :abbreviation %><br>
    <%= f.text_field :abbreviation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing States</h1>

<table>
  <thead>
    <tr>
      <th>Statename</th>
      <th>Abbreviation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.statename %></td>
        <td><%= state.abbreviation %></td>
        <td><%= link_to 'Show', state %></td>
        <td><%= link_to 'Edit', edit_state_path(state) %></td>
        <td><%= link_to 'Destroy', state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Statename:</strong>
  <%= @state.statename %>
</p>

<p>
  <strong>Abbreviation:</strong>
  <%= @state.abbreviation %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>