config/routes.rb
Rails.application.routes.draw do
  get 'dirlogin/pagein'
  post 'dirlogin/pagein'

  get 'dirlogin/pageout'
  post 'dirlogin/pageout'
    
    controller :sessions do
        get 'login' => :new
        post 'login' => :create
        delete 'logout' => :destroy 
    end

  resources :users
  get 'showprodcusts/prodcustin'
  post 'showprodcusts/prodcustin'

  get 'showprodcusts/prodcustout'
  post 'showprodcusts/prodcustout'

  get 'showcustprods/custprodout'
  post 'showcustprods/custprodout'

  get 'showcustprods/custprodin'
  post 'showcustprods/custprodin'

  resources :orders
  resources :products
  resources :customers
  resources :brands
  resources :categories
  resources :states
  get 'dbtables/showdbtables'
    
  get 'sessions/new'

  get 'mainusers/login'

  get 'mainusers/accept'

  get 'mainusers/denial'

  get 'home/index'

  get 'home/catalog'

  get 'flash/flashpage'

    root :to => 'home#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
    validates :brandname, presence: true, uniqueness: true
    validates :brandcontact, presence: true
    
    has_many :product, dependent:  :destroy
    
end

app/models/category.rb
class Category < ActiveRecord::Base
    validates :categoryname, presence: true, uniqueness: true
    validates :categorydescription, presence: true, uniqueness: true
    
    has_many :product, dependent:  :destroy
    
end

app/models/customer.rb
class Customer < ActiveRecord::Base
    validates :firstname, presence: true
    validates :lastname, presence: true
    validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
    validates :phone, presence: true, length: {:is => 10}
    validates :address, presence: true
    validates :city, presence: true
    validates :state_id, presence: true

    has_many :product, :through => :order
    has_many :order, dependent:  :destroy
    
    belongs_to :state
    
    def name
	"#{lastname }, #{firstname}"
    end

    
end

app/models/order.rb
class Order < ActiveRecord::Base
    validates :customer_id, presence: true
    validates :product_id, presence: true
    
    belongs_to :customer
    belongs_to :product
    
end

app/models/product.rb
class Product < ActiveRecord::Base
    validates :productname, presence: true, uniqueness: true
    validates :productimage, presence: true, uniqueness: true
    validates :productdescription, presence: true
    validates :category_id, presence: true
    validates :brand_id, presence: true
    validates :price, presence: true, numericality: true
    validates :status, presence: true
    
    has_many :order
    has_many :customer, :through => :order 
    
    belongs_to :category
    belongs_to :brand
    
end

app/models/state.rb
class State < ActiveRecord::Base
    
end

app/models/user.rb
class User < ActiveRecord::Base
    has_secure_password
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:brandname, :brandcontact)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_filter :authorize
    
  def index
  end

  def catalog
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/dbtables_helper.rb
module DbtablesHelper
end

app/helpers/dirlogin_helper.rb
module DirloginHelper
end

app/helpers/flash_helper.rb
module FlashHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mainusers_helper.rb
module MainusersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/_form.html.erb
<%= form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brandname %><br>
    <%= f.text_field :brandname %>
  </div>
  <div class="field">
    <%= f.label :brandcontact %><br>
    <%= f.text_field :brandcontact %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Brands</h1>

<table>
  <thead>
    <tr>
      <th>Brandname</th>
      <th>Brandcontact</th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.brandname %></td>
        <td><%= brand.brandcontact %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brandname:</strong>
  <%= @brand.brandname %>
</p>

<p>
  <strong>Brandcontact:</strong>
  <%= @brand.brandcontact %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>